# -*- coding: utf-8 -*-
"""Bookstore-Data-Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MzwqBs4hb3US1cqkxoGVRMy1EBvoedkC
"""

import matplotlib.pyplot as plt
import pandas as pd
from google.colab import files
files.upload()
books_df = pd.read_csv("books_dataset.csv")
books_df.head()

books_df.isnull().sum()

books_df['page_count']=books_df['page_count'].fillna(books_df['page_count'].mean())
books_df['rating_out_of_5']=books_df['rating_out_of_5'].fillna(books_df['rating_out_of_5'].mean())
books_df['ratings_count_thousands']=books_df['ratings_count_thousands'].fillna(books_df['ratings_count_thousands'].mean())
books_df['price_usd']=books_df['price_usd'].fillna(books_df['price_usd'].mean())
books_df.isnull().sum()

books_df.dropna(subset=['genre','publication_year'],inplace=True)
books_df.isnull().sum()

genre_avg_price = books_df.groupby('genre')['price_usd'].mean()
print("---Average Book Price by Genre---")
print(genre_avg_price)
top_reads = books_df[books_df['rating_out_of_5'] >= 4.25]
print("\n---Top Reads (Rating >=4.25)---")
top_reads[['title','rating_out_of_5','genre']]



plt.figure(figsize=(10,5))
plt.bar(books_df['title'],books_df['ratings_count_thousands'],color='skyblue',edgecolor='black')
plt.title("Total Number of Ratings per Book Title",fontsize=14,fontweight='bold')
plt.xlabel("Book Title",fontsize=11)
plt.ylabel("Ratings Count (in Thousands)",fontsize=11)
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y',linestyle='--',alpha=0.7)
plt.show()

genre_counts = books_df['genre'].value_counts()
plt.figure(figsize=(6,6))
plt.pie(genre_counts,labels=genre_counts.index,autopct='%1.1f%%')
plt.title("Percentage Breakdown of Books by Genre",fontsize=14,fontweight='bold')
plt.show()